# Generated by Django 4.2 on 2025-08-01 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OPPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_no', models.IntegerField(unique=True)),
                ('op_date', models.DateField()),
                ('patient_id', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('place', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('token_no', models.CharField(blank=True, max_length=20)),
                ('appointment_details', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('qty', models.IntegerField(default=1)),
                ('rate', models.FloatField(default=0)),
                ('tax', models.FloatField(default=0)),
                ('payment_mode', models.CharField(max_length=50)),
                ('received_amount', models.FloatField(default=0)),
                ('balance_amount', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='opticket.description')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='opticket.doctor')),
            ],
        ),
    ]
