# Generated by Django 4.2 on 2025-08-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oppatient',
            name='description',
        ),
        migrations.AddField(
            model_name='oppatient',
            name='description',
            field=models.ManyToManyField(to='opticket.description'),
        ),
    ]
